version: '3'

networks:
  laravel:

services:
  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache
    ports:
      - "8090:80"
    environment:
      TZ: UTC+1
    volumes:
      - ./src:/var/www/html/app
      - ./apache/app.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./logs/apache:/var/log/apache2/access.log
      - ./logs/apache:/var/log/apache2/error.log
      - ./logs/apache:/var/log/apache2/other_vhosts_access.log
    depends_on:
      php:
        condition: service_completed_successfully
    networks:
      - laravel

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./secrets:/secrets
      - ./src:/app
      - ./logs/mysql:/var/log/mysqld.log
      - ./data:/var/lib/mysql
    logging:
      driver: json-file
    environment:
      SERVICE_TAGS: dev-env
    networks:
      - laravel

  php:
    build:
      context: ./php_composer
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/app
      - ./secrets:/secrets
      - ./edit_env.sh:/usr/local/bin/edit_env.sh
      - ./logs/php:/var/log/php.log
    logging:
      driver: json-file
    working_dir: /app
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy
